### ISSUE TITLE
failed to run `noelware/s3-action`: Invalid URL

### ISSUE THREAD

**Issue by tayloraswift** [Noelware/s3-action#841]
i am trying to use the action with these parameters:

https://github.com/tayloraswift/swift-ip/blob/2bd4a61170972eaf747e51343fed98cfcee55866/.github/workflows/Package.yml#L26-L35

```
            -   name: Upload products
                uses: Noelware/s3-action@2.2.6
                with:
                    access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    secret-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    path-format: '/ipinfo/$(file)'
                    bucket: 'swiftinit'
                    files: |
                        country.bson.gz,
                        asn.bson.gz
```

and am running into the error: 

```
Initializing S3 client with bucket [swiftinit] that is from endpoint [s3.amazonaws.com]
initialized s3 client! checking if bucket [swiftinit] exists
Error: failed to run `noelware/s3-action`: Invalid URL
```
https://github.com/tayloraswift/swift-ip/actions/runs/11963717924/job/33354677055#step:5:23

any idea what i am doing wrong here?
